# smart-class/docker-compose.yml(a que roda usando docker hub)
version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: smartclass-test-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: smartclass
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      retries: 5

  backend:
    image: garcia3glxy/smartclass-backend:latest
    container_name: smartclass-test-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://admin:admin@db:5432/smartclass?schema=public"
      JWT_SECRET: "supersecreto"
      PORT: 5000
    ports:
      - "5001:5000"

  frontend:
    image: garcia3glxy/smartclass-frontend:latest
    container_name: smartclass-test-frontend
    depends_on:
      - backend
    ports:
      - "5174:80"

volumes:
  db_data:
